### ISSUE TITLE
1.10.6: Always says "** jack transport off or halted **"

### ISSUE THREAD

**Issue by yurivict** [sjaehn/BChoppr#12]
Other LV2 plugins work fine on the same system.

OS: FreeBSD 12.2

**Comment by sjaehn** [comment]
I can't reproduce it on Ubuntu. Would be nice to hear if others can or can't see the same.
BTW, it's a bit strange as other plugins use the same algorithm.

I guess that you already tried to start and stop Jack transport. Is the white progression line in B.Choppr moving or not?

**Comment by yurivict** [comment]
jackd restart doesn't help.
B.Slizr has the same problem.
Nothing is moving on the screen in B.Choppr.

**Comment by yurivict** [comment]
B.Jumblr has the same problem.

**Comment by sjaehn** [comment]
This makes sense. All my transport-dependent plugins show the message upon the same conditions: 
1. Upon instantiation https://github.com/sjaehn/BChoppr/blob/58bfd48441d7fb5799c0193a817776416e8d9129/src/Message.cpp#L23
2. If the LV2 host-provided time/position parameter drops down below 1.0bpm https://github.com/sjaehn/BChoppr/blob/58bfd48441d7fb5799c0193a817776416e8d9129/src/BChoppr.cpp#L247-L256
3. Or if the LV2 time/position parameter speed provided by the host is set to 0.0 https://github.com/sjaehn/BChoppr/blob/58bfd48441d7fb5799c0193a817776416e8d9129/src/BChoppr.cpp#L265-L274

Otherwise the messages are deleted. In all these cases, a simple atom message will be sent to the UI via the notify port. If only the DSP-UI communication fails, you would clearly hear the effects of the plugins but the error message would stay there.

I think it is somehow related to https://github.com/sjaehn/BSchaffl/issues/17. Which sound like a jalv/jack1 problem.
