### ISSUE TITLE
Crashes Ardour 8

### ISSUE THREAD

**Issue by derkrasseleo** [sjaehn/BChoppr#23]
When I try to load the plugin, Ardour instantly crashes with this error:

```
** (ardour-8.0.0:149601): ERROR **: 23:33:16.823: 
unhandled exception (type std::exception) in signal handler:
what: locale::facet::_S_create_c_locale name not valid

```

Other Plugins (BOops, BSchaffl) work fine..

**Comment by sjaehn** [comment]
Thanks for report. Which OS and version did you use? And which version of B.Choppr? From a third party packager or directly from this github repo?

It may be an UI toolkit related problem as it doesn't seem to happen with B.Ooops and B.Schaffl (which run with an older toolkit).

**Comment by derkrasseleo** [comment]
Arch Linux (6.5.8) and the package from the extra repo (bchoppr 1.12.6-1), the git package from the aur doesn't seem to build, but I'll try to install it

**Comment by derkrasseleo** [comment]
Now I get this error: 
`BChoppr.lv2#GUI: Instantiation failed. locale::facet::_S_create_c_locale name not valid
suil error: Failed to instantiate UI <https://www.jahnichen.de/plugins/lv2/BChoppr#gui> in /usr/local/lib/lv2/BChoppr.lv2/BChoppr_GUI.so`

I still don't get a GUI, but at least it doesn't crash ardour anymore..

**Comment by sjaehn** [comment]
This means that the B.Choppr GUI constructor made the problem. But doesn't tell what exactly happened.

However, I failed to reproduce this problem using Ubuntu 22.04, Ardour 8.0, B.Choppr 1.12.7.

**Comment by derkrasseleo** [comment]
Wierd, I just installed Ardour 8 and b.choppr on a different device and it worked. I also tested reaper on my main machine and I get a similar error:
`jack: created client
jack: non-realtime threads
LC_NUMERIC / LANG is set to 'de_AT.UTF-8', overriding LC_NUMERIC environment to POSIX
jack: activated client
BChoppr.lv2#GUI: Instantiation failed. locale::facet::_S_create_c_locale name not valid
Segmentation fault (core dumped)
`

**Comment by derkrasseleo** [comment]
Interesting, I just disabled `Use Translations` under `Appearance -> Translation` in Ardour settings, now I have a GUI again. Sorry for bothering you..

**Comment by gechoto** [comment]
> Interesting, I just disabled `Use Translations` under `Appearance -> Translation` in Ardour settings, now I have a GUI again.

This is not really a solution - only a workaround - and a bad one since this setting is only in Ardour and effects all plugins

I also have this problem - the plugin crashes Ardour and in Carla the GUI does not show up

In both of these programs it starts working if I start them with `LANG=C` so the problem only occurs if it tries to load translations

Please reopen

**Comment by derkrasseleo** [comment]
Just want to say: In the meanwhile, I had to fully reinstall arch, and currently I'm running bchoppr-1.12.6-1 with Ardour 8.6.0 and don't experience this issue.

**Comment by gechoto** [comment]
> I'm running bchoppr-1.12.6-1 with Ardour 8.6.0

same



> I had to fully reinstall arch

did you also delete all user files (`/home` partition)?
because if not you still have your Ardour configuration from before which means you have disabled `Use Translations` and so the problem is worked around

can you also test with Carla?

**Comment by derkrasseleo** [comment]
> did you also delete all user files (`/home` partition)? because if not you still have your Ardour configuration from before which means you have disabled `Use Translations` and so the problem is worked around
> 
> can you also test with Carla?

Yes, full reinstall, also the GUI works in Carla

**Comment by gechoto** [comment]
ok so I did more testing and think I found the cause

My system is set up in a way that programs are displayed in English but only some things (like time & date format and units) are in my native language

This is just the way I prefer it because some translations in my native language aren't that great and also I use it to learn English better but at the same time I'm not a fan of the American date/time format

But BChoppr does not like this

It only works if I set the system FULLY to ONE language. So if I set everything to English and also use the am/pm 12h clock format, other currency, units...
BChoppr works!

But if I set the system to be a mix of English and my native language it breaks again

Note that I have been using this mixed language setup for about 2-3 years now already and never experienced problems in other software so it is a BChoppr specific issue

**Comment by gechoto** [comment]
huh just to make extra sure... I reinstalled some language related packages, fully updated everything, recreated some configs
also switched away from having my language settings done by the desktop environment, deleted the user-wide settings file and instead did the language settings system wide now (in `/etc` instead of in the home dir)

somehow it works now
not sure what exactly did the trick as I did a number of things but
happy to report that BChoppr works now

It still could maybe be made more robust against crashes around translation related stuff
as I said BChoppr is the only software that crashed with my setup before and I had it for years like that
but overall I guess this can be closed again

**Comment by derkrasseleo** [comment]
Doesn't seem to be related to BChoppr itself, maybe it's an issue in the B.Widgets toolkit. I'll close this now
